name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: 0b86e338-2207-47a9-9770-b6512f28cf96
          heroku_app_name: "lacl-test-backend-api" #Must be unique in Heroku
          heroku_email: "netcordovaleon@gmail.com"
